/**
 * Demo data for RCH Drainage, Northamptonshire.
 * Every address uses a real Northamptonshire town and a correctly formatted NN postcode.
 */
import type {
  AppData,
  Customer,
  CustomerProperty,
  Enquiry,
  Invoice,
  Job,
  JobType,
  JobVariation,
  PriceBookItem,
  Property,
  Quote,
  TaskItem,
  TeamMember,
} from "./domain";

const ORG = "org_rch";

function at(dayOffset: number, hour = 9, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function dayOnly(dayOffset: number): string {
  return at(dayOffset, 12, 0).slice(0, 10);
}

/* ---------- job types (A3) ---------- */

const JOB_TYPE_SEED: Array<[string, string, boolean, boolean, boolean, boolean, number]> = [
  ["jt_blocked", "Blocked drains", true, false, false, true, 90],
  ["jt_cctv", "CCTV drain surveys", true, false, true, true, 90],
  ["jt_jetting", "Drain jetting", true, true, false, true, 120],
  ["jt_emergency", "Emergency call outs", true, false, false, true, 90],
  ["jt_repairs", "Drain repairs", true, true, true, true, 240],
  ["jt_gully", "Gully cleaning", true, false, false, true, 60],
];

export const seedJobTypes: JobType[] = JOB_TYPE_SEED.map(
  ([id, name, before, during, testing, after, duration]) => ({
    id,
    orgId: ORG,
    name,
    isActive: true,
    defaultDurationMinutes: duration,
    requiresBefore: before,
    requiresDuring: during,
    requiresTesting: testing,
    requiresAfter: after,
    minPhotosPerRequiredStage: 1,
    notes: "",
  }),
);

/* ---------- price book ---------- */

export const seedPriceBook: PriceBookItem[] = [
  {
    orgId: ORG,
    id: "pb_callout",
    code: "CALL-MIN",
    name: "Minimum call-out charge",
    unit: "visit",
    unitPrice: 85,
    isVatable: true,
    category: "callout",
  },
  {
    orgId: ORG,
    id: "pb_ooh",
    code: "CALL-OOH",
    name: "Out-of-hours call-out",
    unit: "visit",
    unitPrice: 145,
    isVatable: true,
    category: "callout",
  },
  {
    orgId: ORG,
    id: "pb_hour",
    code: "LAB-HR",
    name: "Hourly labour rate",
    unit: "hour",
    unitPrice: 65,
    isVatable: true,
    category: "labour",
  },
  {
    orgId: ORG,
    id: "pb_half",
    code: "LAB-HALF",
    name: "Half-day rate",
    unit: "half day",
    unitPrice: 210,
    isVatable: true,
    category: "labour",
  },
  {
    orgId: ORG,
    id: "pb_full",
    code: "LAB-DAY",
    name: "Full-day rate",
    unit: "day",
    unitPrice: 390,
    isVatable: true,
    category: "labour",
  },
  {
    orgId: ORG,
    id: "pb_service",
    code: "SRV-BOIL",
    name: "Boiler service",
    unit: "each",
    unitPrice: 95,
    isVatable: true,
    category: "service",
  },
  {
    orgId: ORG,
    id: "pb_flush",
    code: "SRV-FLUSH",
    name: "Power flush (up to 10 rads)",
    unit: "each",
    unitPrice: 545,
    isVatable: true,
    category: "service",
  },
  {
    orgId: ORG,
    id: "pb_drain",
    code: "SRV-DRAIN",
    name: "Drain unblocking",
    unit: "visit",
    unitPrice: 135,
    isVatable: true,
    category: "service",
  },
  {
    orgId: ORG,
    id: "pb_tee22",
    code: "MAT-T22",
    name: "22mm compression tee",
    unit: "each",
    unitPrice: 6.4,
    isVatable: true,
    category: "materials",
  },
  {
    orgId: ORG,
    id: "pb_elbow15",
    code: "MAT-E15",
    name: "15mm compression elbow",
    unit: "each",
    unitPrice: 3.1,
    isVatable: true,
    category: "materials",
  },
  {
    orgId: ORG,
    id: "pb_iso15",
    code: "MAT-ISO15",
    name: "15mm isolation valve",
    unit: "each",
    unitPrice: 4.75,
    isVatable: true,
    category: "materials",
  },
  {
    orgId: ORG,
    id: "pb_trv",
    code: "MAT-TRV",
    name: "Thermostatic radiator valve",
    unit: "each",
    unitPrice: 24.5,
    isVatable: true,
    category: "materials",
  },
  {
    orgId: ORG,
    id: "pb_mixer",
    code: "MAT-MIX",
    name: "Basin mixer tap (mid range)",
    unit: "each",
    unitPrice: 78,
    isVatable: true,
    category: "materials",
  },
];

/* ---------- customers (12) ---------- */

const customers: Customer[] = [
  {
    id: "c1",
    orgId: ORG,
    name: "Karen Whitfield",
    phone: "07700 900123",
    email: "karen.whitfield@example.co.uk",
    kind: "residential",
    isAccountCustomer: false,
    notes: "",
  },
  {
    id: "c2",
    orgId: ORG,
    name: "Dev Patel",
    phone: "07700 900456",
    email: "dev.patel@example.co.uk",
    kind: "residential",
    isAccountCustomer: false,
    notes: "",
  },
  {
    id: "c3",
    orgId: ORG,
    name: "Marie Osei",
    phone: "07700 900321",
    email: "m.osei@example.co.uk",
    kind: "residential",
    isAccountCustomer: false,
    notes: "",
  },
  {
    id: "c4",
    orgId: ORG,
    name: "Tom Bradshaw",
    phone: "07700 900654",
    email: "tom.bradshaw@example.co.uk",
    kind: "residential",
    isAccountCustomer: false,
    notes: "",
  },
  {
    id: "c5",
    orgId: ORG,
    name: "Nene Valley Lettings",
    phone: "01632 960200",
    email: "maintenance@nenevalleylettings.example",
    kind: "landlord",
    isAccountCustomer: true,
    notes: "Three properties on account. 30-day terms.",
  },
  {
    id: "c6",
    orgId: ORG,
    name: "Rushden Community Hall",
    phone: "01632 960880",
    email: "bookings@rushdenhall.example",
    kind: "commercial",
    isAccountCustomer: true,
    notes: "",
  },
  {
    id: "c7",
    orgId: ORG,
    name: "Brackley Bakehouse Ltd",
    phone: "01632 960411",
    email: "accounts@brackleybakehouse.example",
    kind: "commercial",
    isAccountCustomer: true,
    notes: "Invoices to accounts inbox only.",
  },
  {
    id: "c8",
    orgId: ORG,
    name: "Sarah Kettle",
    phone: "07700 900777",
    email: "s.kettle@example.co.uk",
    kind: "residential",
    isAccountCustomer: false,
    notes: "",
  },
  {
    id: "c9",
    orgId: ORG,
    name: "Michael Doyle",
    phone: "07700 900888",
    email: "mdoyle@example.co.uk",
    kind: "residential",
    isAccountCustomer: false,
    notes: "",
  },
  {
    id: "c10",
    orgId: ORG,
    name: "Priya Raman",
    phone: "07700 900999",
    email: "priya.raman@example.co.uk",
    kind: "residential",
    isAccountCustomer: false,
    notes: "",
  },
  {
    id: "c11",
    orgId: ORG,
    name: "Gareth Lloyd",
    phone: "07700 900222",
    email: "g.lloyd@example.co.uk",
    kind: "residential",
    isAccountCustomer: false,
    notes: "",
  },
  {
    id: "c12",
    orgId: ORG,
    name: "Helen Marsden",
    phone: "07700 900444",
    email: "helen.marsden@example.co.uk",
    kind: "residential",
    isAccountCustomer: false,
    notes: "",
  },
];

/* ---------- properties (15) ---------- */

const properties: Property[] = [
  {
    id: "p1",
    orgId: ORG,
    currentCustomerId: "c1",
    line1: "14 Bramble Way",
    town: "Northampton",
    postcode: "NN3 8QT",
    accessNotes: "Key safe by the bin store, code 4417. Large dog in the back garden.",
    boilerMake: "Worcester Bosch",
    boilerModel: "Greenstar 30i",
    boilerSerial: "WB30I-448127",
    boilerInstallYear: 2019,
    nextServiceDate: dayOnly(210),
  },
  {
    id: "p2",
    orgId: ORG,
    currentCustomerId: "c2",
    line1: "Flat 2, 88 Meadow Road",
    town: "Northampton",
    postcode: "NN1 4NH",
    accessNotes: "Buzzer 2. Street parking after 10am only.",
  },
  {
    id: "p3",
    orgId: ORG,
    currentCustomerId: "c3",
    line1: "31 Crockwell Street",
    town: "Kettering",
    postcode: "NN16 8LD",
    accessNotes: "Stopcock under the stairs.",
  },
  {
    id: "p4",
    orgId: ORG,
    currentCustomerId: "c4",
    line1: "9 Hillfoot Close",
    town: "Wellingborough",
    postcode: "NN8 4RJ",
    accessNotes: "",
  },
  {
    id: "p5",
    orgId: ORG,
    currentCustomerId: "c5",
    line1: "6 Ashgate Court",
    town: "Corby",
    postcode: "NN17 2EU",
    accessNotes: "Tenant home from 14:00.",
    boilerMake: "Ideal",
    boilerModel: "Logic Combi 30",
    boilerSerial: "IDL-771204",
    boilerInstallYear: 2021,
    nextServiceDate: dayOnly(95),
  },
  {
    id: "p6",
    orgId: ORG,
    currentCustomerId: "c5",
    line1: "22 Weldon Road",
    town: "Corby",
    postcode: "NN18 9TA",
    accessNotes: "Managing agent holds keys.",
  },
  {
    id: "p7",
    orgId: ORG,
    currentCustomerId: "c5",
    line1: "4 Fitzwilliam Street",
    town: "Rushden",
    postcode: "NN10 0BQ",
    accessNotes: "Rear access via alley.",
  },
  {
    id: "p8",
    orgId: ORG,
    currentCustomerId: "c6",
    line1: "Rushden Community Hall, High Street South",
    town: "Rushden",
    postcode: "NN10 0RB",
    accessNotes: "Caretaker on site 08:00, 16:00.",
  },
  {
    id: "p9",
    orgId: ORG,
    currentCustomerId: "c7",
    line1: "Unit 3, Buckingham Road Industrial Estate",
    town: "Brackley",
    postcode: "NN13 7DP",
    accessNotes: "Deliveries entrance only. No parking on the ramp.",
  },
  {
    id: "p10",
    orgId: ORG,
    currentCustomerId: "c8",
    line1: "77 Ashby Road",
    town: "Daventry",
    postcode: "NN11 0QF",
    accessNotes: "",
    boilerMake: "Vaillant",
    boilerModel: "ecoTEC plus 832",
    boilerSerial: "VLT-556310",
    boilerInstallYear: 2017,
    nextServiceDate: dayOnly(40),
  },
  {
    id: "p11",
    orgId: ORG,
    currentCustomerId: "c9",
    line1: "5 Watling Street East",
    town: "Towcester",
    postcode: "NN12 6BT",
    accessNotes: "Narrow driveway, park on the road.",
  },
  {
    id: "p12",
    orgId: ORG,
    currentCustomerId: "c10",
    line1: "18 Sywell Grove",
    town: "Northampton",
    postcode: "NN5 7PL",
    accessNotes: "",
  },
  {
    id: "p13",
    orgId: ORG,
    currentCustomerId: "c11",
    line1: "42 Rockingham Road",
    town: "Kettering",
    postcode: "NN16 8LA",
    accessNotes: "Cellar access through the kitchen.",
  },
  {
    id: "p14",
    orgId: ORG,
    currentCustomerId: "c12",
    line1: "3 Redwell Court",
    town: "Wellingborough",
    postcode: "NN9 5HN",
    accessNotes: "",
  },
  {
    id: "p15",
    orgId: ORG,
    currentCustomerId: null,
    line1: "12 Kingsthorpe Grove",
    town: "Northampton",
    postcode: "NN2 6PB",
    accessNotes: "Vacant, awaiting sale completion.",
    boilerMake: "Baxi",
    boilerModel: "800 Combi 2",
    boilerSerial: "BX-330918",
    boilerInstallYear: 2022,
  },
];

/* ---------- occupancy history (A4) ---------- */

const customerProperties: CustomerProperty[] = [
  {
    id: "cp1",
    orgId: ORG,
    customerId: "c1",
    propertyId: "p1",
    relationship: "owner_occupier",
    startedOn: "2016-04-02",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp2",
    orgId: ORG,
    customerId: "c2",
    propertyId: "p2",
    relationship: "tenant",
    startedOn: "2023-09-01",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp3",
    orgId: ORG,
    customerId: "c3",
    propertyId: "p3",
    relationship: "owner_occupier",
    startedOn: "2019-11-15",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp4",
    orgId: ORG,
    customerId: "c4",
    propertyId: "p4",
    relationship: "owner_occupier",
    startedOn: "2021-06-30",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp5",
    orgId: ORG,
    customerId: "c5",
    propertyId: "p5",
    relationship: "landlord",
    startedOn: "2018-01-10",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp6",
    orgId: ORG,
    customerId: "c5",
    propertyId: "p6",
    relationship: "landlord",
    startedOn: "2020-03-05",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp7",
    orgId: ORG,
    customerId: "c5",
    propertyId: "p7",
    relationship: "landlord",
    startedOn: "2022-08-22",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp8",
    orgId: ORG,
    customerId: "c6",
    propertyId: "p8",
    relationship: "managing_agent",
    startedOn: "2017-02-01",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp9",
    orgId: ORG,
    customerId: "c7",
    propertyId: "p9",
    relationship: "owner_occupier",
    startedOn: "2019-05-20",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp10",
    orgId: ORG,
    customerId: "c8",
    propertyId: "p10",
    relationship: "owner_occupier",
    startedOn: "2015-07-14",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp11",
    orgId: ORG,
    customerId: "c9",
    propertyId: "p11",
    relationship: "owner_occupier",
    startedOn: "2020-10-02",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp12",
    orgId: ORG,
    customerId: "c10",
    propertyId: "p12",
    relationship: "owner_occupier",
    startedOn: "2024-02-09",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp13",
    orgId: ORG,
    customerId: "c11",
    propertyId: "p13",
    relationship: "owner_occupier",
    startedOn: "2013-03-18",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp14",
    orgId: ORG,
    customerId: "c12",
    propertyId: "p14",
    relationship: "owner_occupier",
    startedOn: "2022-12-01",
    endedOn: null,
    isCurrent: true,
  },
  {
    id: "cp15",
    orgId: ORG,
    customerId: "c9",
    propertyId: "p15",
    relationship: "owner_occupier",
    startedOn: "2011-05-06",
    endedOn: "2025-11-28",
    isCurrent: false,
  },
  {
    id: "cp16",
    orgId: ORG,
    customerId: "c12",
    propertyId: "p12",
    relationship: "tenant",
    startedOn: "2019-01-15",
    endedOn: "2024-01-31",
    isCurrent: false,
  },
];

/* ---------- enquiries (6) ---------- */

const enquiries: Enquiry[] = [
  {
    id: "e1",
    orgId: ORG,
    reference: "E-0104",
    customerId: "c3",
    propertyId: "p3",
    jobTypeId: "jt_emergency",
    contactName: "Marie Osei",
    phone: "07700 900321",
    rawAddress: "31 Crockwell Street, Kettering, NN16 8LD",
    description:
      "No hot water at all since this morning, water pooling under the boiler. Two young children in the house.",
    isEmergency: true,
    urgency: "emergency",
    valueBand: "medium",
    status: "new",
    receivedAt: at(0, 7, 12),
  },
  {
    id: "e2",
    orgId: ORG,
    reference: "E-0105",
    customerId: "c4",
    propertyId: "p4",
    jobTypeId: "jt_repairs",
    contactName: "Tom Bradshaw",
    phone: "07700 900654",
    rawAddress: "9 Hillfoot Close, Wellingborough, NN8 4RJ",
    description: "Wants a quote for a full bathroom suite install, flexible on dates.",
    isEmergency: false,
    urgency: "flexible",
    valueBand: "large",
    status: "qualified",
    receivedAt: at(0, 9, 5),
  },
  {
    id: "e3",
    orgId: ORG,
    reference: "E-0103",
    customerId: "c10",
    propertyId: "p12",
    jobTypeId: "jt_blocked",
    contactName: "Priya Raman",
    phone: "07700 900999",
    rawAddress: "18 Sywell Grove, Northampton, NN5 7PL",
    description: "Outside drain backing up when the washing machine empties.",
    isEmergency: false,
    urgency: "urgent",
    valueBand: "small",
    status: "needs_contact",
    receivedAt: at(-1, 16, 40),
  },
  {
    id: "e4",
    orgId: ORG,
    reference: "E-0102",
    customerId: "c6",
    propertyId: "p8",
    jobTypeId: "jt_gully",
    contactName: "Rushden Community Hall",
    phone: "01632 960880",
    rawAddress: "High Street South, Rushden, NN10 0RB",
    description: "Four radiators in the main hall stay cold at the bottom.",
    isEmergency: false,
    urgency: "standard",
    valueBand: "medium",
    status: "quoted",
    receivedAt: at(-4, 11, 20),
  },
  {
    id: "e5",
    orgId: ORG,
    reference: "E-0101",
    customerId: "c11",
    propertyId: "p13",
    jobTypeId: "jt_repairs",
    contactName: "Gareth Lloyd",
    phone: "07700 900222",
    rawAddress: "42 Rockingham Road, Kettering, NN16 8LA",
    description: "Damp patch on the cellar ceiling, suspect a pinhole leak in the feed.",
    isEmergency: false,
    urgency: "urgent",
    valueBand: "small",
    status: "converted",
    receivedAt: at(-6, 8, 15),
  },
  {
    id: "e6",
    orgId: ORG,
    reference: "E-0100",
    customerId: "c9",
    propertyId: "p11",
    jobTypeId: "jt_cctv",
    contactName: "Michael Doyle",
    phone: "07700 900888",
    rawAddress: "5 Watling Street East, Towcester, NN12 6BT",
    description: "Asked about a new combi boiler, decided to go with a national installer.",
    isEmergency: false,
    urgency: "flexible",
    valueBand: "large",
    status: "declined",
    declineReason: "Customer accepted a cheaper national quote.",
    receivedAt: at(-12, 14, 0),
  },
];

/* ---------- quotes (4) ---------- */

const quotes: Quote[] = [
  {
    id: "q1",
    orgId: ORG,
    quoteNumber: "Q-0031",
    customerId: "c4",
    propertyId: "p4",
    enquiryId: "e2",
    jobTypeId: "jt_repairs",
    status: "draft",
    lines: [
      {
        id: "ql1",
        description: "Bathroom installation labour (4 days)",
        quantity: 4,
        unitPrice: 390,
        isVatable: true,
      },
      {
        id: "ql2",
        description: "Basin mixer tap (mid range)",
        quantity: 1,
        unitPrice: 78,
        isVatable: true,
      },
    ],
    depositRule: "percentage",
    depositPercentage: 75,
    depositFixedAmount: 0,
    stagePayments: [],
    lockedAt: null,
    createdAt: at(-1, 17, 0),
    validUntil: dayOnly(28),
  },
  {
    id: "q2",
    orgId: ORG,
    quoteNumber: "Q-0032",
    customerId: "c6",
    propertyId: "p8",
    enquiryId: "e4",
    jobTypeId: "jt_gully",
    status: "sent",
    lines: [
      {
        id: "ql3",
        description: "Power flush (up to 10 rads)",
        quantity: 1,
        unitPrice: 545,
        isVatable: true,
      },
      {
        id: "ql4",
        description: "Thermostatic radiator valve",
        quantity: 4,
        unitPrice: 24.5,
        isVatable: true,
      },
    ],
    depositRule: "percentage",
    depositPercentage: 75,
    depositFixedAmount: 0,
    stagePayments: [],
    lockedAt: null,
    createdAt: at(-3, 10, 0),
    validUntil: dayOnly(25),
  },
  {
    id: "q3",
    orgId: ORG,
    quoteNumber: "Q-0033",
    customerId: "c11",
    propertyId: "p13",
    enquiryId: "e5",
    jobTypeId: "jt_repairs",
    status: "accepted",
    lines: [
      { id: "ql5", description: "Hourly labour rate", quantity: 3, unitPrice: 65, isVatable: true },
      {
        id: "ql6",
        description: "22mm compression tee",
        quantity: 2,
        unitPrice: 6.4,
        isVatable: true,
      },
    ],
    depositRule: "percentage",
    depositPercentage: 75,
    depositFixedAmount: 0,
    stagePayments: [],
    lockedAt: at(-5, 9, 30),
    createdAt: at(-6, 9, 0),
    validUntil: dayOnly(20),
  },
  {
    id: "q4",
    orgId: ORG,
    quoteNumber: "Q-0034",
    customerId: "c7",
    propertyId: "p9",
    enquiryId: null,
    jobTypeId: "jt_jetting",
    status: "sent",
    lines: [
      { id: "ql7", description: "Full-day rate", quantity: 2, unitPrice: 390, isVatable: true },
      {
        id: "ql8",
        description: "Pipework and fittings allowance",
        quantity: 1,
        unitPrice: 180,
        isVatable: true,
      },
    ],
    depositRule: "account_customer",
    depositPercentage: 75,
    depositFixedAmount: 0,
    depositWaivedBy: "Ray Chapman",
    depositWaivedAt: at(-2, 15, 10),
    stagePayments: [],
    lockedAt: null,
    createdAt: at(-2, 15, 0),
    validUntil: dayOnly(26),
  },
];

/* ---------- jobs (8) ---------- */

const jobs: Job[] = [
  {
    id: "j1",
    orgId: ORG,
    jobNumber: "J-0042",
    customerId: "c3",
    propertyId: "p3",
    quoteId: null,
    enquiryId: "e1",
    jobTypeId: "jt_emergency",
    title: "No hot water, water pooling under boiler",
    reportedIssue: "No hot water at all since this morning, water pooling under the boiler.",
    scope: "Attend, isolate, diagnose and make safe.",
    assignedToId: "u1",
    isEmergency: true,
    status: "booked",
    scheduledStart: at(0, 8, 30),
    durationMinutes: 90,
    workDoneNotes: "",
    partsUsedNotes: "",
    recommendations: "",
    testResults: "",
    photos: [],
    materials: [
      {
        id: "m1",
        name: "15mm isolation valve",
        quantity: 2,
        isJobCritical: true,
        isCollected: true,
      },
    ],
    waivers: [],
    completedAt: null,
  },
  {
    id: "j2",
    orgId: ORG,
    jobNumber: "J-0043",
    customerId: "c5",
    propertyId: "p5",
    quoteId: null,
    enquiryId: null,
    jobTypeId: "jt_cctv",
    title: "Annual boiler service",
    reportedIssue: "Landlord annual service due.",
    scope: "Full service and safety check on Ideal Logic Combi 30.",
    assignedToId: "u1",
    isEmergency: false,
    status: "booked",
    scheduledStart: at(0, 11, 0),
    durationMinutes: 60,
    workDoneNotes: "",
    partsUsedNotes: "",
    recommendations: "",
    testResults: "",
    photos: [],
    materials: [],
    waivers: [],
    completedAt: null,
  },
  {
    id: "j3",
    orgId: ORG,
    jobNumber: "J-0044",
    customerId: "c1",
    propertyId: "p1",
    quoteId: null,
    enquiryId: null,
    jobTypeId: "jt_repairs",
    title: "Replace bathroom mixer tap",
    reportedIssue: "Mixer tap dripping constantly.",
    scope: "Swap tap, replace isolator if seized.",
    assignedToId: "u2",
    isEmergency: false,
    status: "booked",
    scheduledStart: at(0, 14, 30),
    durationMinutes: 60,
    workDoneNotes: "",
    partsUsedNotes: "",
    recommendations: "",
    testResults: "",
    photos: [],
    materials: [
      {
        id: "m2",
        name: "Basin mixer tap (customer supplied)",
        quantity: 1,
        isJobCritical: true,
        isCollected: false,
      },
    ],
    waivers: [],
    completedAt: null,
  },
  {
    id: "j4",
    orgId: ORG,
    jobNumber: "J-0041",
    customerId: "c11",
    propertyId: "p13",
    quoteId: "q3",
    enquiryId: "e5",
    jobTypeId: "jt_repairs",
    title: "Cellar pinhole leak repair",
    reportedIssue: "Damp patch on the cellar ceiling, suspect a pinhole leak in the feed.",
    scope: "Cut out and replace the affected 22mm section.",
    assignedToId: "u1",
    isEmergency: false,
    status: "in_progress",
    scheduledStart: at(0, 7, 30),
    durationMinutes: 120,
    workDoneNotes: "Isolated at the cellar valve, cut out 600mm of corroded 22mm.",
    partsUsedNotes: "2x 22mm compression tee",
    recommendations: "",
    testResults: "",
    photos: [
      {
        id: "ph1",
        stage: "before",
        label: "Damp patch on cellar ceiling",
        capturedAt: at(0, 7, 45),
      },
      { id: "ph2", stage: "during", label: "Corroded section removed", capturedAt: at(0, 8, 20) },
    ],
    materials: [
      {
        id: "m3",
        name: "22mm compression tee",
        quantity: 2,
        isJobCritical: true,
        isCollected: true,
      },
    ],
    waivers: [],
    completedAt: null,
  },
  {
    id: "j5",
    orgId: ORG,
    jobNumber: "J-0040",
    customerId: "c8",
    propertyId: "p10",
    quoteId: null,
    enquiryId: null,
    jobTypeId: "jt_jetting",
    title: "Intermittent lockout on Vaillant ecoTEC",
    reportedIssue: "Boiler locking out with F.28 two or three times a week.",
    scope: "Diagnose ignition fault and repair.",
    assignedToId: "u2",
    isEmergency: false,
    status: "awaiting_close_out",
    scheduledStart: at(-1, 9, 0),
    durationMinutes: 120,
    workDoneNotes: "Replaced ignition electrode and cleaned the condensate trap.",
    partsUsedNotes: "Ignition electrode kit",
    recommendations: "Service due in 6 weeks, book it in.",
    testResults: "Gas rate 30.2 kW, working pressure 1.4 bar, flue analysis pass.",
    photos: [
      { id: "ph3", stage: "before", label: "Fault code on display", capturedAt: at(-1, 9, 10) },
      { id: "ph4", stage: "during", label: "Old electrode removed", capturedAt: at(-1, 9, 55) },
      { id: "ph5", stage: "testing", label: "Flue analyser reading", capturedAt: at(-1, 10, 40) },
    ],
    materials: [],
    waivers: [],
    completedAt: null,
  },
  {
    id: "j6",
    orgId: ORG,
    jobNumber: "J-0039",
    customerId: "c10",
    propertyId: "p12",
    quoteId: null,
    enquiryId: "e3",
    jobTypeId: "jt_blocked",
    title: "Blocked external drain",
    reportedIssue: "Outside drain backing up when the washing machine empties.",
    scope: "Rod and jet the external run.",
    assignedToId: "u1",
    isEmergency: false,
    status: "return_required",
    scheduledStart: at(-2, 13, 0),
    durationMinutes: 90,
    workDoneNotes:
      "Rodded the run, partial clear only. Root ingress suspected at the boundary chamber.",
    partsUsedNotes: "",
    recommendations: "CCTV survey needed at the boundary chamber.",
    testResults: "",
    photos: [
      {
        id: "ph6",
        stage: "before",
        label: "Standing water in chamber",
        capturedAt: at(-2, 13, 10),
      },
      { id: "ph7", stage: "after", label: "Chamber part cleared", capturedAt: at(-2, 14, 15) },
    ],
    materials: [],
    waivers: [],
    completedAt: null,
  },
  {
    id: "j7",
    orgId: ORG,
    jobNumber: "J-0038",
    customerId: "c7",
    propertyId: "p9",
    quoteId: null,
    enquiryId: null,
    jobTypeId: "jt_jetting",
    title: "Reroute cold feed around new oven bay",
    reportedIssue: "Cold feed runs through the new oven bay.",
    scope: "Reroute 22mm cold feed and reinstate.",
    assignedToId: "u2",
    isEmergency: false,
    status: "complete",
    scheduledStart: at(-8, 8, 0),
    durationMinutes: 300,
    workDoneNotes: "Rerouted 4.5m of 22mm cold feed above the ceiling line, clipped and insulated.",
    partsUsedNotes: "4.5m 22mm copper, 6 elbows, pipe insulation",
    recommendations: "Lag the loft run before winter.",
    testResults: "Pressure held at 3 bar for 15 minutes.",
    photos: [
      {
        id: "ph8",
        stage: "before",
        label: "Original feed through oven bay",
        capturedAt: at(-8, 8, 10),
      },
      { id: "ph9", stage: "during", label: "New run clipped in place", capturedAt: at(-8, 10, 30) },
      { id: "ph10", stage: "after", label: "Bay clear and reinstated", capturedAt: at(-8, 12, 40) },
    ],
    materials: [],
    waivers: [],
    completedAt: at(-8, 13, 0),
  },
  {
    id: "j8",
    orgId: ORG,
    jobNumber: "J-0037",
    customerId: "c5",
    propertyId: "p6",
    quoteId: null,
    enquiryId: null,
    jobTypeId: "jt_repairs",
    title: "Kitchen tap replacement",
    reportedIssue: "Tenant reports kitchen tap seized.",
    scope: "Replace kitchen mixer tap.",
    assignedToId: "u1",
    isEmergency: false,
    status: "complete",
    scheduledStart: at(-11, 15, 0),
    durationMinutes: 60,
    workDoneNotes: "Replaced seized kitchen mixer and both isolators.",
    partsUsedNotes: "1x kitchen mixer, 2x 15mm isolation valve",
    recommendations: "",
    testResults: "",
    photos: [
      { id: "ph11", stage: "before", label: "Seized tap", capturedAt: at(-11, 15, 5) },
      { id: "ph12", stage: "after", label: "New mixer fitted", capturedAt: at(-11, 15, 50) },
    ],
    materials: [],
    waivers: [],
    completedAt: at(-11, 16, 0),
  },
];

/* ---------- variations ---------- */

const variations: JobVariation[] = [
  {
    id: "v1",
    orgId: ORG,
    jobId: "j4",
    description:
      "Second corroded section found behind the cellar steps, additional 1m replacement.",
    amount: 95,
    isVatable: true,
    status: "pending",
    approvedAt: null,
    approvedByNote: "",
    createdBy: "Ray Chapman",
    createdAt: at(0, 8, 40),
  },
  {
    id: "v2",
    orgId: ORG,
    jobId: "j7",
    description: "Additional insulation to the loft run.",
    amount: 48,
    isVatable: true,
    status: "approved",
    approvedAt: at(-8, 11, 0),
    approvedByNote: "Agreed on the phone with Jodie at Brackley Bakehouse, 11:00.",
    createdBy: "Sam Iqbal",
    createdAt: at(-8, 10, 50),
  },
];

/* ---------- invoices (5) ---------- */

const invoices: Invoice[] = [
  {
    id: "i1",
    orgId: ORG,
    invoiceNumber: "INV-0088",
    customerId: "c7",
    propertyId: "p9",
    jobId: "j7",
    status: "part_paid",
    lines: [
      {
        id: "il1",
        description: "Pipework reroute labour",
        quantity: 1,
        unitPrice: 1170,
        isVatable: true,
      },
      {
        id: "il2",
        description: "Variation, loft run insulation",
        quantity: 1,
        unitPrice: 48,
        isVatable: true,
      },
    ],
    payments: [{ id: "pay1", amount: 700, paidAt: at(-6, 10, 0), method: "bank_transfer" }],
    issuedAt: at(-7, 9, 0),
    dueAt: at(23, 9, 0),
  },
  {
    id: "i2",
    orgId: ORG,
    invoiceNumber: "INV-0087",
    customerId: "c5",
    propertyId: "p6",
    jobId: "j8",
    status: "paid",
    lines: [
      {
        id: "il3",
        description: "Kitchen tap replacement",
        quantity: 1,
        unitPrice: 148,
        isVatable: true,
      },
    ],
    payments: [{ id: "pay2", amount: 177.6, paidAt: at(-9, 12, 0), method: "bank_transfer" }],
    issuedAt: at(-10, 9, 0),
    dueAt: at(20, 9, 0),
  },
  {
    id: "i3",
    orgId: ORG,
    invoiceNumber: "INV-0086",
    customerId: "c1",
    propertyId: "p1",
    jobId: null,
    status: "overdue",
    lines: [
      {
        id: "il4",
        description: "Emergency call-out and leak repair",
        quantity: 1,
        unitPrice: 285,
        isVatable: true,
      },
    ],
    payments: [],
    issuedAt: at(-52, 9, 0),
    dueAt: at(-22, 9, 0),
  },
  {
    id: "i4",
    orgId: ORG,
    invoiceNumber: "INV-0085",
    customerId: "c6",
    propertyId: "p8",
    jobId: null,
    status: "overdue",
    lines: [
      {
        id: "il5",
        description: "Radiator diagnostics visit",
        quantity: 1,
        unitPrice: 165,
        isVatable: true,
      },
    ],
    payments: [],
    issuedAt: at(-60, 9, 0),
    dueAt: at(-30, 9, 0),
  },
  {
    id: "i5",
    orgId: ORG,
    invoiceNumber: "INV-0089",
    customerId: "c8",
    propertyId: "p10",
    jobId: "j5",
    status: "issued",
    lines: [
      {
        id: "il6",
        description: "Boiler repair, ignition electrode",
        quantity: 1,
        unitPrice: 235,
        isVatable: true,
      },
    ],
    payments: [],
    issuedAt: at(-1, 17, 0),
    dueAt: at(29, 17, 0),
  },
];

/* ---------- tasks (6) ---------- */

const tasks: TaskItem[] = [
  {
    id: "t1",
    orgId: ORG,
    title: "Order 22mm compression tees",
    status: "due",
    dueDate: dayOnly(0),
  },
  {
    id: "t2",
    orgId: ORG,
    title: "Chase Q-0032 with Rushden Community Hall",
    status: "open",
    dueDate: dayOnly(0),
    linkedType: "quote",
    linkedId: "q2",
  },
  {
    id: "t3",
    orgId: ORG,
    title: "Book CCTV survey for 18 Sywell Grove",
    status: "waiting",
    dueDate: dayOnly(2),
    linkedType: "job",
    linkedId: "j6",
  },
  {
    id: "t4",
    orgId: ORG,
    title: "Chase INV-0086, 22 days overdue",
    status: "monitoring",
    dueDate: dayOnly(1),
    linkedType: "invoice",
    linkedId: "i3",
  },
  {
    id: "t5",
    orgId: ORG,
    title: "Send completion pack to Brackley Bakehouse",
    status: "complete",
    dueDate: dayOnly(-7),
    linkedType: "job",
    linkedId: "j7",
  },
  { id: "t6", orgId: ORG, title: "Renew van insurance", status: "open", dueDate: dayOnly(9) },
];

const team: TeamMember[] = [
  { id: "u1", orgId: ORG, name: "Ray Chapman", role: "owner" },
  { id: "u2", orgId: ORG, name: "Sam Iqbal", role: "engineer" },
  { id: "u3", orgId: ORG, name: "Jodie Fenn", role: "office_admin" },
  { id: "u4", orgId: ORG, name: "Dan Priestley", role: "subcontractor" },
];

/* ---------- generated volume ---------- */

function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rand = rng(20260805);
const pick = <T>(list: T[]): T => list[Math.floor(rand() * list.length)]!;
const pad = (n: number, width: number) => String(n).padStart(width, "0");

const FIRST_NAMES = [
  "Alan",
  "Bethany",
  "Carl",
  "Denise",
  "Eddie",
  "Fiona",
  "Gavin",
  "Hannah",
  "Ian",
  "Jodie",
  "Kieran",
  "Laura",
  "Martin",
  "Nadia",
  "Owen",
  "Paula",
  "Quentin",
  "Rhian",
  "Simon",
  "Tanya",
  "Umar",
  "Verity",
  "Wayne",
  "Yvonne",
  "Zack",
  "Bill",
  "Clare",
  "Derek",
  "Elaine",
  "Frank",
];
const LAST_NAMES = [
  "Ashby",
  "Bentley",
  "Cartwright",
  "Dunmore",
  "Ellery",
  "Fairhurst",
  "Gadsby",
  "Hollowell",
  "Ingram",
  "Jelley",
  "Kilborn",
  "Lumsden",
  "Maplethorpe",
  "Newcombe",
  "Oakley",
  "Pickering",
  "Quainton",
  "Rigby",
  "Southam",
  "Tebbutt",
  "Underwood",
  "Vann",
  "Wilby",
  "Yardley",
];
const TOWNS: Array<[string, string[]]> = [
  ["Northampton", ["NN1", "NN2", "NN3", "NN4", "NN5", "NN6", "NN7"]],
  ["Kettering", ["NN15", "NN16"]],
  ["Wellingborough", ["NN8", "NN9"]],
  ["Corby", ["NN17", "NN18"]],
  ["Rushden", ["NN10"]],
  ["Daventry", ["NN11"]],
  ["Towcester", ["NN12"]],
  ["Brackley", ["NN13"]],
  ["Desborough", ["NN14"]],
  ["Higham Ferrers", ["NN10"]],
  ["Irthlingborough", ["NN9"]],
  ["Raunds", ["NN9"]],
  ["Burton Latimer", ["NN15"]],
  ["Earls Barton", ["NN6"]],
  ["Wootton", ["NN4"]],
];
const STREETS = [
  "Bective Road",
  "Harborough Road",
  "Wellingborough Road",
  "Kingsley Park Terrace",
  "Booth Lane",
  "Hardingstone Lane",
  "Gold Street",
  "Silver Street",
  "Kettering Road",
  "Overstone Road",
  "Sheep Street",
  "Windmill Avenue",
  "Pytchley Road",
  "Finedon Road",
  "Cottingham Road",
  "Stanion Lane",
  "Newton Road",
  "Bedford Road",
  "Abington Grove",
  "Church Way",
  "Manor Close",
  "Orchard Rise",
  "Barnwell Terrace",
  "Occupation Road",
  "Spencer Bridge Road",
  "Trinity Avenue",
  "St Giles Street",
  "Millers Park",
  "Grafton Way",
  "Weedon Road",
];
const COMPANY_NAMES = [
  "Nene Lettings Group",
  "Sywell Property Services",
  "Corby Trade Park Ltd",
  "Kettering Care Homes",
  "Daventry Bakers Ltd",
  "Towcester Estates",
  "Brackley Motor Works",
  "Rushden Retail Ltd",
];

const JOB_TITLES = [
  "Blocked kitchen sink",
  "Leaking radiator valve",
  "Annual boiler service",
  "Replace kitchen mixer",
  "Cylinder overflow",
  "Toilet not flushing",
  "Low boiler pressure",
  "Burst pipe under sink",
  "Shower running cold",
  "Outside tap install",
  "Soil stack blockage",
  "Immersion heater fault",
  "Rerun cold feed",
  "Replace stopcock",
  "Power flush system",
];
const TASK_TITLES = [
  "Chase deposit payment",
  "Order parts for boiler swap",
  "Book gas safe certificate",
  "Call customer back about dates",
  "Send completion pack",
  "Chase overdue invoice",
  "Confirm skip delivery",
  "Order 15mm copper",
  "Arrange CCTV drain survey",
  "Update price book rates",
  "Van service booking",
  "Return spare parts to merchant",
];

const PB_EXTRA: Array<[string, string, string, number, PriceBookItem["category"]]> = [
  ["MAT-C15", "15mm copper pipe (3m)", "length", 12.4, "materials"],
  ["MAT-C22", "22mm copper pipe (3m)", "length", 18.9, "materials"],
  ["MAT-C28", "28mm copper pipe (3m)", "length", 27.5, "materials"],
  ["MAT-PTFE", "PTFE tape", "roll", 1.2, "materials"],
  ["MAT-FLUX", "Soldering flux", "tin", 6.8, "materials"],
  ["MAT-SOLD", "Lead free solder", "reel", 14.2, "materials"],
  ["MAT-STOP", "Stopcock 15mm", "each", 11.5, "materials"],
  ["MAT-BALL", "Ball valve 22mm", "each", 9.9, "materials"],
  ["MAT-PUMP", "Central heating pump", "each", 132, "materials"],
  ["MAT-EXPV", "Expansion vessel", "each", 64, "materials"],
  ["MAT-PRV", "Pressure relief valve", "each", 28, "materials"],
  ["MAT-DIVR", "Diverter valve cartridge", "each", 88, "materials"],
  ["MAT-THERM", "Room thermostat", "each", 54, "materials"],
  ["MAT-TRVX", "TRV head only", "each", 12.75, "materials"],
  ["MAT-RAD6", "Radiator 600x1000 double", "each", 96, "materials"],
  ["MAT-TOWEL", "Towel rail chrome", "each", 74, "materials"],
  ["MAT-WCPAN", "Close coupled WC pan", "each", 118, "materials"],
  ["MAT-CIST", "WC cistern and fittings", "each", 62, "materials"],
  ["MAT-BASIN", "Basin and pedestal", "each", 104, "materials"],
  ["MAT-SHOWR", "Shower mixer bar", "each", 132, "materials"],
  ["MAT-TRAP", "Bottle trap 40mm", "each", 5.4, "materials"],
  ["MAT-WASTE", "Waste pipe 40mm (3m)", "length", 8.2, "materials"],
  ["MAT-SEAL", "Sanitary silicone", "tube", 7.1, "materials"],
  ["MAT-INHIB", "System inhibitor", "bottle", 16.5, "materials"],
  ["MAT-MAGF", "Magnetic filter", "each", 89, "materials"],
  ["SRV-CERT", "Gas safety certificate", "each", 75, "service"],
  ["SRV-LAND", "Landlord safety check", "each", 89, "service"],
  ["SRV-CCTV", "CCTV drain survey", "visit", 195, "service"],
  ["SRV-DESC", "Descale and clean", "each", 110, "service"],
  ["LAB-EVE", "Evening labour rate", "hour", 85, "labour"],
  ["LAB-WKND", "Weekend labour rate", "hour", 95, "labour"],
  ["CALL-BANK", "Bank holiday call-out", "visit", 185, "callout"],
];

const extraPriceBook: PriceBookItem[] = PB_EXTRA.map(
  ([code, name, unit, unitPrice, category], i) => ({
    orgId: ORG,
    id: `pb_x${i + 1}`,
    code,
    name,
    unit,
    unitPrice,
    isVatable: true,
    category,
  }),
);

const priceBook = seedPriceBook;

const extraCustomers: Customer[] = Array.from({ length: 48 }, (_, i) => {
  const n = i + 13;
  const isCompany = i % 8 === 7;
  const name = isCompany
    ? `${COMPANY_NAMES[i % COMPANY_NAMES.length]!} ${Math.floor(i / COMPANY_NAMES.length) + 1}`
    : `${FIRST_NAMES[i % FIRST_NAMES.length]!} ${LAST_NAMES[(i * 5) % LAST_NAMES.length]!}`;
  const kind: Customer["kind"] = isCompany
    ? "commercial"
    : i % 6 === 5
      ? "landlord"
      : "residential";
  return {
    id: `c${n}`,
    orgId: ORG,
    name,
    phone: isCompany
      ? `01632 960${pad((i * 7) % 1000, 3)}`
      : `07700 9${pad(1000 + i * 13, 5).slice(0, 5)}`,
    email: `${name.toLowerCase().replace(/[^a-z]+/g, ".")}@example.co.uk`,
    kind,
    isAccountCustomer: kind !== "residential",
    notes: "",
  };
});

const allCustomers = [...customers, ...extraCustomers];

const extraProperties: Property[] = Array.from({ length: 65 }, (_, i) => {
  const n = i + 16;
  const [town, prefixes] = TOWNS[i % TOWNS.length]!;
  const owner = allCustomers[(i * 3) % allCustomers.length]!;
  return {
    id: `p${n}`,
    orgId: ORG,
    currentCustomerId: owner.id,
    line1: `${1 + ((i * 7) % 96)} ${STREETS[i % STREETS.length]!}`,
    town,
    postcode: `${prefixes[i % prefixes.length]!} ${1 + (i % 9)}${"ABDEFGHJLNPQRSTUWXYZ"[i % 20]!}${"ABDEFGHJLNPQRSTUWXYZ"[(i * 3) % 20]!}`,
    accessNotes: i % 4 === 0 ? "Call ahead, side gate access." : "",
  };
});

const allProperties = [...properties, ...extraProperties];

const extraCustomerProperties: CustomerProperty[] = extraProperties.map((property, i) => ({
  id: `cp_x${i + 1}`,
  orgId: ORG,
  customerId: property.currentCustomerId!,
  propertyId: property.id,
  relationship: i % 5 === 0 ? "landlord" : i % 7 === 0 ? "tenant" : "owner_occupier",
  startedOn: `20${16 + (i % 9)}-0${1 + (i % 9)}-1${i % 9}`,
  endedOn: null,
  isCurrent: true,
}));

const GEN_JOB_STATUSES: Job["status"][] = [
  "ready_to_book",
  "booked",
  "en_route",
  "on_site",
  "in_progress",
  "awaiting_close_out",
  "complete",
  "complete",
  "complete",
  "return_required",
  "cancelled",
];

const jobTypeIds = JOB_TYPE_SEED.map(([id]) => id);
const engineerIds = ["u1", "u2", "u4"];

const extraJobs: Job[] = Array.from({ length: 112 }, (_, i) => {
  const property = allProperties[i % allProperties.length]!;
  const status = GEN_JOB_STATUSES[i % GEN_JOB_STATUSES.length]!;
  const dayOffset =
    status === "complete" || status === "cancelled"
      ? -90 + ((i * 7) % 85)
      : status === "ready_to_book" || status === "booked"
        ? 1 + (i % 20)
        : -(i % 5);
  const start = at(dayOffset, 7 + (i % 9), (i % 4) * 15);
  const done = status === "complete";
  return {
    id: `j_x${i + 1}`,
    orgId: ORG,
    jobNumber: `J-${pad(100 + i, 4)}`,
    customerId: property.currentCustomerId ?? "c1",
    propertyId: property.id,
    quoteId: null,
    enquiryId: null,
    jobTypeId: jobTypeIds[i % jobTypeIds.length]!,
    title: JOB_TITLES[i % JOB_TITLES.length]!,
    reportedIssue: `${JOB_TITLES[i % JOB_TITLES.length]!} reported by the customer.`,
    scope: "Attend, diagnose and repair.",
    assignedToId: engineerIds[i % engineerIds.length]!,
    isEmergency: false,
    status,
    scheduledStart: start,
    durationMinutes: 60 + (i % 4) * 30,
    workDoneNotes: done ? "Work carried out and tested on site." : "",
    partsUsedNotes: done ? "Standard fittings from van stock." : "",
    recommendations: "",
    testResults: done ? "System pressure holding, no leaks." : "",
    photos: done
      ? [
          { id: `ph_x${i}a`, stage: "before" as const, label: "Before work", capturedAt: start },
          { id: `ph_x${i}b`, stage: "after" as const, label: "After work", capturedAt: start },
        ]
      : [],
    materials: [],
    waivers: [],
    completedAt: done ? at(dayOffset, 16, 0) : null,
  };
});

const GEN_QUOTE_STATUSES: Quote["status"][] = [
  "draft",
  "sent",
  "viewed",
  "accepted",
  "declined",
  "expired",
  "approval_required",
  "superseded",
];

const extraQuotes: Quote[] = Array.from({ length: 36 }, (_, i) => {
  const property = allProperties[(i * 2) % allProperties.length]!;
  const status = GEN_QUOTE_STATUSES[i % GEN_QUOTE_STATUSES.length]!;
  const created = at(-70 + i * 2, 10, 0);
  return {
    id: `q_x${i + 1}`,
    orgId: ORG,
    quoteNumber: `Q-${pad(100 + i, 4)}`,
    customerId: property.currentCustomerId ?? "c1",
    propertyId: property.id,
    enquiryId: null,
    jobTypeId: jobTypeIds[i % jobTypeIds.length]!,
    status,
    lines: [
      {
        id: `ql_x${i}a`,
        description: "Labour",
        quantity: 1 + (i % 4),
        unitPrice: 65,
        isVatable: true,
      },
      {
        id: `ql_x${i}b`,
        description: "Parts and fittings",
        quantity: 1,
        unitPrice: 40 + (i % 9) * 25,
        isVatable: true,
      },
    ],
    depositRule: "percentage",
    depositPercentage: 75,
    depositFixedAmount: 0,
    stagePayments: [],
    lockedAt: status === "accepted" ? created : null,
    createdAt: created,
    validUntil: dayOnly(-70 + i * 2 + 28),
  };
});

const GEN_INVOICE_STATUSES: Invoice["status"][] = [
  "issued",
  "part_paid",
  "paid",
  "paid",
  "overdue",
  "disputed",
  "payment_plan",
  "draft",
  "written_off",
  "credited",
  "overdue",
];

const extraInvoices: Invoice[] = Array.from({ length: 55 }, (_, i) => {
  const property = allProperties[(i * 5) % allProperties.length]!;
  const status = GEN_INVOICE_STATUSES[i % GEN_INVOICE_STATUSES.length]!;
  const total = 95 + (i % 14) * 65;
  const issuedOffset = status === "overdue" ? -75 + (i % 40) : -60 + ((i * 3) % 58);
  return {
    id: `i_x${i + 1}`,
    orgId: ORG,
    invoiceNumber: `INV-${pad(100 + i, 4)}`,
    customerId: property.currentCustomerId ?? "c1",
    propertyId: property.id,
    jobId: null,
    status,
    lines: [
      {
        id: `il_x${i}`,
        description: "Plumbing works as agreed",
        quantity: 1,
        unitPrice: total,
        isVatable: true,
      },
    ],
    payments:
      status === "paid"
        ? [
            {
              id: `pay_x${i}`,
              amount: total * 1.2,
              paidAt: at(issuedOffset + 12, 11, 0),
              method: "bank_transfer" as const,
            },
          ]
        : status === "part_paid" || status === "payment_plan"
          ? [
              {
                id: `pay_x${i}`,
                amount: Math.round(total * 0.4),
                paidAt: at(issuedOffset + 9, 11, 0),
                method: "bank_transfer" as const,
              },
            ]
          : [],
    issuedAt: status === "draft" ? null : at(issuedOffset, 9, 0),
    dueAt: status === "draft" ? null : at(issuedOffset + 30, 9, 0),
  };
});

const extraTasks: TaskItem[] = Array.from({ length: 24 }, (_, i) => ({
  id: `t_x${i + 1}`,
  orgId: ORG,
  title: `${TASK_TITLES[i % TASK_TITLES.length]!}, ${allCustomers[(i * 5) % allCustomers.length]!.name}`,
  status: (["open", "waiting", "monitoring", "due", "complete", "open"] as TaskItem["status"][])[
    i % 6
  ]!,
  dueDate: dayOnly(-6 + (i % 21)),
}));

export function createSeedData(): AppData {
  return {
    org: {
      id: ORG,
      name: "RCH Drainage",
      tradingName: "RCH Drainage",
      phone: "01632 960100",
      email: "office@rchdrainage.example",
      town: "Northampton, Northamptonshire",
      vatRate: 0.2,
      defaultDepositRule: "percentage",
      defaultDepositPercentage: 75,
      minimumCalloutItemId: "pb_callout",
    },
    team,
    currentUserId: "u1",
    jobTypes: seedJobTypes,
    customers: allCustomers,
    properties: allProperties,
    customerProperties: [...customerProperties, ...extraCustomerProperties],
    enquiries,
    priceBook: [...priceBook, ...extraPriceBook],
    quotes: [...quotes, ...extraQuotes],
    jobs: [...jobs, ...extraJobs],
    variations,
    invoices: [...invoices, ...extraInvoices],
    tasks: [...tasks, ...extraTasks],
    activity: [
      {
        id: "a1",
        orgId: ORG,
        entityType: "quote",
        entityId: "q3",
        message: "Quote Q-0033 accepted and locked",
        actor: "Ray Chapman",
        at: at(-5, 9, 30),
      },
      {
        id: "a2",
        orgId: ORG,
        entityType: "quote",
        entityId: "q4",
        message: "Deposit waived, account customer",
        actor: "Ray Chapman",
        at: at(-2, 15, 10),
      },
      {
        id: "a3",
        orgId: ORG,
        entityType: "job",
        entityId: "j7",
        message: "Job J-0038 marked complete",
        actor: "Sam Iqbal",
        at: at(-8, 13, 0),
      },
      {
        id: "a4",
        orgId: ORG,
        entityType: "invoice",
        entityId: "i1",
        message: "Payment of £700.00 recorded by bank transfer",
        actor: "Jodie Fenn",
        at: at(-6, 10, 0),
      },
      {
        id: "a5",
        orgId: ORG,
        entityType: "job",
        entityId: "j6",
        message: "Job J-0039 set to return required",
        actor: "Ray Chapman",
        at: at(-2, 14, 30),
      },
    ],
    counters: { quote: 136, job: 212, invoice: 155, enquiry: 105 },
  };
}
