/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBookingPageRouteImport } from './routes/app.booking-page'
import { Route as AppEnquiriesRouteImport } from './routes/app.enquiries'
import { Route as AppJobTypesRouteImport } from './routes/app.job-types'
import { Route as AppMoneyRouteImport } from './routes/app.money'
import { Route as AppMoreRouteImport } from './routes/app.more'
import { Route as AppPriceBookRouteImport } from './routes/app.price-book'
import { Route as AppQuotesRouteImport } from './routes/app.quotes'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as BookOrgSlugRouteImport } from './routes/book.$orgSlug'
import { Route as EmbedOrgSlugRouteImport } from './routes/embed.$orgSlug'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerOnboardingRouteImport } from './routes/owner.onboarding'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as AppCustomersIndexRouteImport } from './routes/app.customers.index'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/app.customers.$customerId'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/app.invoices.$invoiceId'
import { Route as AppJobsIndexRouteImport } from './routes/app.jobs.index'
import { Route as BookOrgSlugIndexRouteImport } from './routes/book.$orgSlug.index'
import { Route as BookOrgSlugReportRouteImport } from './routes/book.$orgSlug.report'
import { Route as OwnerAccountsIndexRouteImport } from './routes/owner.accounts.index'
import { Route as OwnerAccountsAccountIdRouteImport } from './routes/owner.accounts.$accountId'
import { Route as AppJobsJobIdIndexRouteImport } from './routes/app.jobs.$jobId.index'
import { Route as AppJobsJobIdPackRouteImport } from './routes/app.jobs.$jobId.pack'
import { Route as BookOrgSlugAreasIndexRouteImport } from './routes/book.$orgSlug.areas.index'
import { Route as BookOrgSlugAreasTownSlugRouteImport } from './routes/book.$orgSlug.areas.$townSlug'
import { Route as BookOrgSlugSentRefRouteImport } from './routes/book.$orgSlug.sent.$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingPageRoute = AppBookingPageRouteImport.update({
  id: '/booking-page',
  path: '/booking-page',
  getParentRoute: () => AppRoute,
} as any)
const AppEnquiriesRoute = AppEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AppRoute,
} as any)
const AppJobTypesRoute = AppJobTypesRouteImport.update({
  id: '/job-types',
  path: '/job-types',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyRoute = AppMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceBookRoute = AppPriceBookRouteImport.update({
  id: '/price-book',
  path: '/price-book',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesRoute = AppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookOrgSlugRoute = BookOrgSlugRouteImport.update({
  id: '/book/$orgSlug',
  path: '/book/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedOrgSlugRoute = EmbedOrgSlugRouteImport.update({
  id: '/embed/$orgSlug',
  path: '/embed/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOnboardingRoute = OwnerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const BookOrgSlugIndexRoute = BookOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookOrgSlugRoute,
} as any)
const BookOrgSlugReportRoute = BookOrgSlugReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => BookOrgSlugRoute,
} as any)
const OwnerAccountsIndexRoute = OwnerAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAccountsAccountIdRoute = OwnerAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => OwnerRoute,
} as any)
const AppJobsJobIdIndexRoute = AppJobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdPackRoute = AppJobsJobIdPackRouteImport.update({
  id: '/jobs/$jobId/pack',
  path: '/jobs/$jobId/pack',
  getParentRoute: () => AppRoute,
} as any)
const BookOrgSlugAreasIndexRoute = BookOrgSlugAreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => BookOrgSlugRoute,
} as any)
const BookOrgSlugAreasTownSlugRoute =
  BookOrgSlugAreasTownSlugRouteImport.update({
    id: '/areas/$townSlug',
    path: '/areas/$townSlug',
    getParentRoute: () => BookOrgSlugRoute,
  } as any)
const BookOrgSlugSentRefRoute = BookOrgSlugSentRefRouteImport.update({
  id: '/sent/$ref',
  path: '/sent/$ref',
  getParentRoute: () => BookOrgSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/booking-page': typeof AppBookingPageRoute
  '/app/enquiries': typeof AppEnquiriesRoute
  '/app/job-types': typeof AppJobTypesRoute
  '/app/money': typeof AppMoneyRoute
  '/app/more': typeof AppMoreRoute
  '/app/price-book': typeof AppPriceBookRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/book/$orgSlug': typeof BookOrgSlugRouteWithChildren
  '/embed/$orgSlug': typeof EmbedOrgSlugRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/app/': typeof AppIndexRoute
  '/book/': typeof BookIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/book/$orgSlug/report': typeof BookOrgSlugReportRoute
  '/owner/accounts/$accountId': typeof OwnerAccountsAccountIdRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/book/$orgSlug/': typeof BookOrgSlugIndexRoute
  '/owner/accounts/': typeof OwnerAccountsIndexRoute
  '/app/jobs/$jobId/pack': typeof AppJobsJobIdPackRoute
  '/book/$orgSlug/areas/$townSlug': typeof BookOrgSlugAreasTownSlugRoute
  '/book/$orgSlug/sent/$ref': typeof BookOrgSlugSentRefRoute
  '/app/jobs/$jobId/': typeof AppJobsJobIdIndexRoute
  '/book/$orgSlug/areas/': typeof BookOrgSlugAreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/booking-page': typeof AppBookingPageRoute
  '/app/enquiries': typeof AppEnquiriesRoute
  '/app/job-types': typeof AppJobTypesRoute
  '/app/money': typeof AppMoneyRoute
  '/app/more': typeof AppMoreRoute
  '/app/price-book': typeof AppPriceBookRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/embed/$orgSlug': typeof EmbedOrgSlugRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/app': typeof AppIndexRoute
  '/book': typeof BookIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/book/$orgSlug/report': typeof BookOrgSlugReportRoute
  '/owner/accounts/$accountId': typeof OwnerAccountsAccountIdRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/jobs': typeof AppJobsIndexRoute
  '/book/$orgSlug': typeof BookOrgSlugIndexRoute
  '/owner/accounts': typeof OwnerAccountsIndexRoute
  '/app/jobs/$jobId/pack': typeof AppJobsJobIdPackRoute
  '/book/$orgSlug/areas/$townSlug': typeof BookOrgSlugAreasTownSlugRoute
  '/book/$orgSlug/sent/$ref': typeof BookOrgSlugSentRefRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdIndexRoute
  '/book/$orgSlug/areas': typeof BookOrgSlugAreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/booking-page': typeof AppBookingPageRoute
  '/app/enquiries': typeof AppEnquiriesRoute
  '/app/job-types': typeof AppJobTypesRoute
  '/app/money': typeof AppMoneyRoute
  '/app/more': typeof AppMoreRoute
  '/app/price-book': typeof AppPriceBookRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/book/$orgSlug': typeof BookOrgSlugRouteWithChildren
  '/embed/$orgSlug': typeof EmbedOrgSlugRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/app/': typeof AppIndexRoute
  '/book/': typeof BookIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/book/$orgSlug/report': typeof BookOrgSlugReportRoute
  '/owner/accounts/$accountId': typeof OwnerAccountsAccountIdRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/book/$orgSlug/': typeof BookOrgSlugIndexRoute
  '/owner/accounts/': typeof OwnerAccountsIndexRoute
  '/app/jobs/$jobId/pack': typeof AppJobsJobIdPackRoute
  '/book/$orgSlug/areas/$townSlug': typeof BookOrgSlugAreasTownSlugRoute
  '/book/$orgSlug/sent/$ref': typeof BookOrgSlugSentRefRoute
  '/app/jobs/$jobId/': typeof AppJobsJobIdIndexRoute
  '/book/$orgSlug/areas/': typeof BookOrgSlugAreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contact'
    | '/faq'
    | '/features'
    | '/login'
    | '/owner'
    | '/pricing'
    | '/signup'
    | '/sitemap.xml'
    | '/app/booking-page'
    | '/app/enquiries'
    | '/app/job-types'
    | '/app/money'
    | '/app/more'
    | '/app/price-book'
    | '/app/quotes'
    | '/app/settings'
    | '/app/tasks'
    | '/book/$orgSlug'
    | '/embed/$orgSlug'
    | '/owner/onboarding'
    | '/owner/settings'
    | '/app/'
    | '/book/'
    | '/owner/'
    | '/app/customers/$customerId'
    | '/app/invoices/$invoiceId'
    | '/book/$orgSlug/report'
    | '/owner/accounts/$accountId'
    | '/app/customers/'
    | '/app/jobs/'
    | '/book/$orgSlug/'
    | '/owner/accounts/'
    | '/app/jobs/$jobId/pack'
    | '/book/$orgSlug/areas/$townSlug'
    | '/book/$orgSlug/sent/$ref'
    | '/app/jobs/$jobId/'
    | '/book/$orgSlug/areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/sitemap.xml'
    | '/app/booking-page'
    | '/app/enquiries'
    | '/app/job-types'
    | '/app/money'
    | '/app/more'
    | '/app/price-book'
    | '/app/quotes'
    | '/app/settings'
    | '/app/tasks'
    | '/embed/$orgSlug'
    | '/owner/onboarding'
    | '/owner/settings'
    | '/app'
    | '/book'
    | '/owner'
    | '/app/customers/$customerId'
    | '/app/invoices/$invoiceId'
    | '/book/$orgSlug/report'
    | '/owner/accounts/$accountId'
    | '/app/customers'
    | '/app/jobs'
    | '/book/$orgSlug'
    | '/owner/accounts'
    | '/app/jobs/$jobId/pack'
    | '/book/$orgSlug/areas/$townSlug'
    | '/book/$orgSlug/sent/$ref'
    | '/app/jobs/$jobId'
    | '/book/$orgSlug/areas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contact'
    | '/faq'
    | '/features'
    | '/login'
    | '/owner'
    | '/pricing'
    | '/signup'
    | '/sitemap.xml'
    | '/app/booking-page'
    | '/app/enquiries'
    | '/app/job-types'
    | '/app/money'
    | '/app/more'
    | '/app/price-book'
    | '/app/quotes'
    | '/app/settings'
    | '/app/tasks'
    | '/book/$orgSlug'
    | '/embed/$orgSlug'
    | '/owner/onboarding'
    | '/owner/settings'
    | '/app/'
    | '/book/'
    | '/owner/'
    | '/app/customers/$customerId'
    | '/app/invoices/$invoiceId'
    | '/book/$orgSlug/report'
    | '/owner/accounts/$accountId'
    | '/app/customers/'
    | '/app/jobs/'
    | '/book/$orgSlug/'
    | '/owner/accounts/'
    | '/app/jobs/$jobId/pack'
    | '/book/$orgSlug/areas/$townSlug'
    | '/book/$orgSlug/sent/$ref'
    | '/app/jobs/$jobId/'
    | '/book/$orgSlug/areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BookOrgSlugRoute: typeof BookOrgSlugRouteWithChildren
  EmbedOrgSlugRoute: typeof EmbedOrgSlugRoute
  BookIndexRoute: typeof BookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/booking-page': {
      id: '/app/booking-page'
      path: '/booking-page'
      fullPath: '/app/booking-page'
      preLoaderRoute: typeof AppBookingPageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/enquiries': {
      id: '/app/enquiries'
      path: '/enquiries'
      fullPath: '/app/enquiries'
      preLoaderRoute: typeof AppEnquiriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/job-types': {
      id: '/app/job-types'
      path: '/job-types'
      fullPath: '/app/job-types'
      preLoaderRoute: typeof AppJobTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/money': {
      id: '/app/money'
      path: '/money'
      fullPath: '/app/money'
      preLoaderRoute: typeof AppMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/more': {
      id: '/app/more'
      path: '/more'
      fullPath: '/app/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/price-book': {
      id: '/app/price-book'
      path: '/price-book'
      fullPath: '/app/price-book'
      preLoaderRoute: typeof AppPriceBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotes': {
      id: '/app/quotes'
      path: '/quotes'
      fullPath: '/app/quotes'
      preLoaderRoute: typeof AppQuotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$orgSlug': {
      id: '/book/$orgSlug'
      path: '/book/$orgSlug'
      fullPath: '/book/$orgSlug'
      preLoaderRoute: typeof BookOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$orgSlug': {
      id: '/embed/$orgSlug'
      path: '/embed/$orgSlug'
      fullPath: '/embed/$orgSlug'
      preLoaderRoute: typeof EmbedOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/onboarding': {
      id: '/owner/onboarding'
      path: '/onboarding'
      fullPath: '/owner/onboarding'
      preLoaderRoute: typeof OwnerOnboardingRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/$customerId': {
      id: '/app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices/$invoiceId': {
      id: '/app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/app/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs/': {
      id: '/app/jobs/'
      path: '/jobs'
      fullPath: '/app/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/$orgSlug/': {
      id: '/book/$orgSlug/'
      path: '/'
      fullPath: '/book/$orgSlug/'
      preLoaderRoute: typeof BookOrgSlugIndexRouteImport
      parentRoute: typeof BookOrgSlugRoute
    }
    '/book/$orgSlug/report': {
      id: '/book/$orgSlug/report'
      path: '/report'
      fullPath: '/book/$orgSlug/report'
      preLoaderRoute: typeof BookOrgSlugReportRouteImport
      parentRoute: typeof BookOrgSlugRoute
    }
    '/owner/accounts/': {
      id: '/owner/accounts/'
      path: '/accounts'
      fullPath: '/owner/accounts/'
      preLoaderRoute: typeof OwnerAccountsIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/accounts/$accountId': {
      id: '/owner/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/owner/accounts/$accountId'
      preLoaderRoute: typeof OwnerAccountsAccountIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/app/jobs/$jobId/': {
      id: '/app/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/app/jobs/$jobId/'
      preLoaderRoute: typeof AppJobsJobIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs/$jobId/pack': {
      id: '/app/jobs/$jobId/pack'
      path: '/jobs/$jobId/pack'
      fullPath: '/app/jobs/$jobId/pack'
      preLoaderRoute: typeof AppJobsJobIdPackRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/$orgSlug/areas/': {
      id: '/book/$orgSlug/areas/'
      path: '/areas'
      fullPath: '/book/$orgSlug/areas/'
      preLoaderRoute: typeof BookOrgSlugAreasIndexRouteImport
      parentRoute: typeof BookOrgSlugRoute
    }
    '/book/$orgSlug/areas/$townSlug': {
      id: '/book/$orgSlug/areas/$townSlug'
      path: '/areas/$townSlug'
      fullPath: '/book/$orgSlug/areas/$townSlug'
      preLoaderRoute: typeof BookOrgSlugAreasTownSlugRouteImport
      parentRoute: typeof BookOrgSlugRoute
    }
    '/book/$orgSlug/sent/$ref': {
      id: '/book/$orgSlug/sent/$ref'
      path: '/sent/$ref'
      fullPath: '/book/$orgSlug/sent/$ref'
      preLoaderRoute: typeof BookOrgSlugSentRefRouteImport
      parentRoute: typeof BookOrgSlugRoute
    }
  }
}

interface AppRouteChildren {
  AppBookingPageRoute: typeof AppBookingPageRoute
  AppEnquiriesRoute: typeof AppEnquiriesRoute
  AppJobTypesRoute: typeof AppJobTypesRoute
  AppMoneyRoute: typeof AppMoneyRoute
  AppMoreRoute: typeof AppMoreRoute
  AppPriceBookRoute: typeof AppPriceBookRoute
  AppQuotesRoute: typeof AppQuotesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppJobsJobIdPackRoute: typeof AppJobsJobIdPackRoute
  AppJobsJobIdIndexRoute: typeof AppJobsJobIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingPageRoute: AppBookingPageRoute,
  AppEnquiriesRoute: AppEnquiriesRoute,
  AppJobTypesRoute: AppJobTypesRoute,
  AppMoneyRoute: AppMoneyRoute,
  AppMoreRoute: AppMoreRoute,
  AppPriceBookRoute: AppPriceBookRoute,
  AppQuotesRoute: AppQuotesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppJobsJobIdPackRoute: AppJobsJobIdPackRoute,
  AppJobsJobIdIndexRoute: AppJobsJobIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OwnerRouteChildren {
  OwnerOnboardingRoute: typeof OwnerOnboardingRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerAccountsAccountIdRoute: typeof OwnerAccountsAccountIdRoute
  OwnerAccountsIndexRoute: typeof OwnerAccountsIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerOnboardingRoute: OwnerOnboardingRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerAccountsAccountIdRoute: OwnerAccountsAccountIdRoute,
  OwnerAccountsIndexRoute: OwnerAccountsIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface BookOrgSlugRouteChildren {
  BookOrgSlugReportRoute: typeof BookOrgSlugReportRoute
  BookOrgSlugIndexRoute: typeof BookOrgSlugIndexRoute
  BookOrgSlugAreasTownSlugRoute: typeof BookOrgSlugAreasTownSlugRoute
  BookOrgSlugSentRefRoute: typeof BookOrgSlugSentRefRoute
  BookOrgSlugAreasIndexRoute: typeof BookOrgSlugAreasIndexRoute
}

const BookOrgSlugRouteChildren: BookOrgSlugRouteChildren = {
  BookOrgSlugReportRoute: BookOrgSlugReportRoute,
  BookOrgSlugIndexRoute: BookOrgSlugIndexRoute,
  BookOrgSlugAreasTownSlugRoute: BookOrgSlugAreasTownSlugRoute,
  BookOrgSlugSentRefRoute: BookOrgSlugSentRefRoute,
  BookOrgSlugAreasIndexRoute: BookOrgSlugAreasIndexRoute,
}

const BookOrgSlugRouteWithChildren = BookOrgSlugRoute._addFileChildren(
  BookOrgSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BookOrgSlugRoute: BookOrgSlugRouteWithChildren,
  EmbedOrgSlugRoute: EmbedOrgSlugRoute,
  BookIndexRoute: BookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
